language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  cargo build --verbose;
  cargo test --verbose;
  cargo clean;
  cargo build --features ssl --verbose; 
  cargo test --features ssl --verbose;
